#!/bin/bash
# Generates a source whose output is far larger than the output buffer, and
# whose every kind of fixup lands a long way behind the cursor.
#
# WHY THIS EXISTS. The differential corpus cannot see the streaming work. Its
# largest output is test/corpus/Includes/tests/large_include.expect at 153,602
# bytes, and that comes from a single INCBIN with three source lines and no
# forward references at all. Every other source in the tree assembles to under
# 32 KB. So once the output buffer becomes a window onto a longer file, 559
# sources will stay green while proving nothing about the flush, the slide or
# the patches that have to be applied on disk afterwards.
#
# This is the source that does prove it. It is built so that, at any window
# size smaller than its output:
#
#   * most of the file has been written and forgotten by the time anything is
#     patched -- every global fixup is settled at the end of the source, so its
#     site is behind the window whenever the output is larger than one;
#   * every fixup width is represented: three-byte absolute (`ld hl, label`),
#     the four-byte data form (`dl`), and the three folds that go into the
#     opcode byte rather than after it -- `bit`, `rst` and `im` against an EQU
#     defined at the very end;
#   * one scope is deliberately longer than a window, with a local forward
#     reference across it. Locals are drained at every global label, so they
#     are normally near the cursor; this is the one shape where a local fixup
#     has to survive its own scope being flushed;
#   * reservations are scattered all through it and the file's only FILLBYTE is
#     its last line, so every one of them is a run whose value is not known
#     until the end -- the case that has to be written back across the whole
#     file rather than patched in place;
#   * `ORG` padding appears too, which is written where it stands rather than
#     reserved, so the two are not confused.
#
# Deterministic, with no randomness: the text at index i is a pure function of
# i, so regenerating gives a byte-identical file and a comparison made today
# can be repeated next year. If this ever needs to change, add a generator
# rather than editing this one -- the same rule test/bench/gen_synth.sh states,
# and for the same reason.
#
#   test/gen_window.sh [blocks] > window.s
#
# The default is sized to about 256 KB of output, which is four times the
# window the design settles on and twenty times the largest thing in the
# corpus. test/window.sh is what runs it against the reference.
set -euo pipefail

BLOCKS="${1:-2800}"

# How far into the filler the long scope's local label sits. Larger than any
# window the assembler is likely to use, so the reference to it is made in one
# window and settled in another.
LONGFILL="${2:-98304}"

awk -v n="$BLOCKS" -v longfill="$LONGFILL" '
BEGIN {
    nblocks = n
    print "; Generated by test/gen_window.sh -- do not edit."
    print "; Output is deliberately larger than the assembler'\''s output buffer."
    print "    .assume adl=1"
    print "    .org 0x40000"
    print ""

    # The head refers to the very last thing in the file, so these fixups span
    # the whole output no matter how large it is.
    print "head:"
    print "    jp   tail_end"
    print "    ld   hl, tail_data"
    print "    ld   de, tail_end"
    print "    dl   tail_end"
    print "    dl   tail_data"
    print "    bit  FAR_BIT, a"
    print "    rst  FAR_RST"
    print "    im   FAR_IM"
    print ""

    for (i = 0; i < n; i++) {
        blk(i)
        # One scope longer than a window, placed a third of the way in so that
        # there is output on both sides of it.
        if (i == int(n / 3)) {
            longscope()
        }
    }

    # Everything above points here. The EQUs are last so that the three folds
    # are still unsettled for the whole of the file.
    print "FAR_BIT: EQU 5"
    print "FAR_RST: EQU 0x18"
    print "FAR_IM:  EQU 1"
    print "tail_data:"
    print "    db 0xDE, 0xAD, 0xBE, 0xEF"
    print "tail_end:"
    print "    ret"
    # The file'\''s only FILLBYTE, and its last line: every reservation above it
    # is a run whose value is decided from here.
    print "    fillbyte 0xAA"
}

# About ninety bytes of output, with a fixup of each kind and a reservation.
function blk(i) {
    # nblocks is the generator argument; awk has no lexical scope worth the name.
    printf "blk_%d:\n", i
    # Forward to the next block, and to the end of the file. The second is the
    # one that is still unsettled when the first has long been written. The
    # last block wraps to the first, which makes its reference a backward one
    # -- settled where it stands, and a control for the rest.
    printf "    ld   hl, blk_%d\n", (i + 1) % nblocks
    print  "    ld   de, tail_end"
    print  "    dl   tail_end"
    print  "    bit  FAR_BIT, a"
    # A local scope: a backward reference and a short forward one, both of
    # which are settled at the next global label and so stay near the cursor.
    print  "@lp:"
    print  "    ld   a, (hl)"
    print  "    inc  hl"
    print  "    djnz @lp"
    print  "    jr   @done"
    print  "    nop"
    print  "@done:"
    print  "    ld   bc, 0x1234"
    print  "    blkb 64, 0x5A"
    # Reserved, not written, and its value is not decided until the FILLBYTE on
    # the last line of the file.
    print  "    ds   2"
    print  "    align 4"
    print  "    nop"
    print  ""
}

# A single scope longer than any window, with a local reference across it.
function longscope(   left) {
    print "longscope:"
    print "    ld   hl, @far"
    print "    ld   de, @far"
    # Written in blocks rather than one huge one, because a single reservation
    # larger than the window is its own case and belongs in its own test.
    left = longfill
    while (left > 0) {
        if (left > 4096) {
            print "    blkb 4096, 0x33"
            left -= 4096
        } else {
            printf "    blkb %d, 0x33\n", left
            left = 0
        }
    }
    print "@far:"
    print "    nop"
    # Padding that is written where it stands, so that it is not confused with
    # the reservations above.
    print "    org  $+7"
    print "    nop"
    print ""
}
'
