#!/bin/bash
# Generates a source at isa_real's label density whose every reference is as
# far from its definition as the file allows.
#
# WHAT "WORST CASE" MEANS HERE. A one-pass assembler settles a global forward
# reference at the end of the source, and with a window the site of that
# reference has long since been written out and forgotten. So the worst shape
# for it is the one where *every* reference is forward and every definition is
# at the very end: every fixup is a patch behind the window, and the sweep that
# applies them has to touch the whole file rather than the tail of it.
#
# test/gen_window.sh is the correctness fixture -- it holds one of every kind
# of fixup, so that something is wrong if any of them is mishandled. This one
# is the pressure fixture: one shape, repeated, at a density taken from a real
# program, to find out what that costs rather than whether it works.
#
# THE DENSITY IS MEASURED, NOT GUESSED. test/bench/gen_isa.sh's `real`
# distribution, at 200 KB of source, is 16,432 lines of which 611 define a
# label (3.7%) and 3,332 branch (20.3%), and it assembles to 0.198 bytes of
# output per byte of source. A block here is 27 lines with one definition and
# five branches, which is 3.7% and 18.5%.
#
# Deterministic: the text at index i is a pure function of i. Regenerating
# gives a byte-identical file, so a timing taken today can be repeated.
#
#   test/gen_worst.sh <target output bytes> > worst.s
#
# The size is what the source is sized *for*; the generator prints nothing
# about it, and the exact output is whatever the assembler makes of it. The kit
# that uses this reports both.
set -euo pipefail

WANT="${1:-65536}"

# Measured, not counted by hand: a block is 50 bytes of output and about 730
# of source, so a target of N bytes needs N/50 blocks and 14.6N of source. A
# megabyte of output is therefore 7.6 MB of source, which is the price of
# asking for this density at that size.
PER_BLOCK=50

BLOCKS=$(( (WANT + PER_BLOCK - 1) / PER_BLOCK ))

awk -v n="$BLOCKS" '
BEGIN {
    print "; Generated by test/gen_worst.sh -- do not edit."
    print "; Every reference is forward and every definition is at the end."
    print "    .assume adl=1"
    print "    .org 0x40000"
    print ""
    for (i = 0; i < n; i++) {
        blk(i)
    }
    # Every target in the file, defined here and nowhere else. Nothing above
    # this point can be settled until the assembler reaches it.
    print "far_a:"
    print "    nop"
    print "far_b:"
    print "    nop"
    print "far_c:"
    print "    nop"
    print "far_d:"
    print "    nop"
    print "far_e:"
    print "    ret"
}

# Twenty-seven lines: one label definition, five branches to labels that do not
# exist yet, and twenty-one instructions that do not refer to anything.
function blk(i) {
    printf "w%d:\n", i                 # 1 definition
    print "    ld   hl, far_a"         # 5 references, four bytes each
    print "    call far_b"
    print "    jp   far_c"
    print "    ld   de, far_d"
    print "    ld   bc, far_e"
    print "    nop"                    # 21 that refer to nothing
    print "    inc  hl"
    print "    add  a, b"
    print "    ld   a, 0x42"
    print "    dec  c"
    print "    ld   ix, 0x1234"
    print "    or   a"
    print "    push af"
    print "    pop  af"
    print "    ld   (hl), a"
    print "    xor  a"
    print "    cp   b"
    print "    sbc  a, c"
    print "    rlca"
    print "    ex   de, hl"
    print "    scf"
    print "    ccf"
    print "    and  0x0F"
    print "    sub  d"
    print "    adc  a, e"
    print "    ld   sp, 0x8000"
    print ""
}
'
