#!/bin/bash
# Generates a source at isa_real's label density whose every reference is as
# far from its definition as the file allows.
#
# WHAT "WORST CASE" MEANS HERE. A one-pass assembler settles a global forward
# reference at the end of the source, and with a window the site of that
# reference has long since been written out and forgotten. So the worst shape
# for it is the one where *every* reference is forward and every definition is
# at the very end: every fixup is a patch behind the window, and the sweep that
# applies them has to touch the whole file rather than the tail of it.
#
# test/gen_window.sh is the correctness fixture -- it holds one of every kind
# of fixup, so that something is wrong if any of them is mishandled. This one
# is the pressure fixture: one shape, repeated, at a density taken from a real
# program, to find out what that costs rather than whether it works.
#
# THE DENSITY IS MEASURED, NOT GUESSED. test/bench/gen_isa.sh's `real`
# distribution, at 200 KB of source, is 16,432 lines of which 611 define a
# label (3.7%) and 3,332 branch (20.3%), and it assembles to 0.198 bytes of
# output per byte of source. A block here is 27 lines with one definition and
# five branches, which is 3.7% and 18.5%.
#
# Deterministic: the text at index i is a pure function of i. Regenerating
# gives a byte-identical file, so a timing taken today can be repeated.
#
#   test/gen_worst.sh <target output bytes> [span] > worst.s
#
# The size is what the source is sized *for*; the generator prints nothing
# about it, and the exact output is whatever the assembler makes of it. The kit
# that uses this reports both.
#
# SPAN, AND WHY IT IS THE AXIS THAT MATTERS. With every definition at the end,
# every reference in the file is outstanding at once: the fixup list holds one
# record per reference and nothing can be settled until the last line is read.
# That is the wall, and it is a wall no early settling can move -- which makes
# the shape useless for saying where the ceiling *is* for code somebody wrote.
#
# `span` is how many blocks a reference reaches forward: the five targets are
# redefined every `span` blocks, so a reference reaches at most that far and
# the records for it are settled that soon. Peak outstanding is then about
# five times the span whatever the file's size, which is the number the sweep
# in fix_add exists to hold down.
#
#   span 0    the default, and exactly the file this generated before the knob
#             existed -- so a timing taken then is comparable with one taken
#             now. Every reference outstanding, 100% live.
#   span N    targets every N blocks, which is N*50 bytes of reach.
#
# For scale: at this density BBC BASIC's median reference reaches 605 bytes
# and its peak live is 490 records, which is a span of about 12; a CP/M
# implementation reaches 4,513 bytes with 950 live, a span of about 90.
#
# WHAT IT FOUND, so that the next reader does not re-find it. There were two
# ceilings here and they were different things. The span decides how many
# records are live at once -- about five times it -- and a span whose five
# times does not fit the list is refused at any size at all. That one is real
# and belongs to a one-pass assembler.
#
# The second was an accident of the late list's shape: a record could only be
# settled early while its site was still in the window, so every flush
# stranded what the last sweep had not reached, and a source was refused at
# about four windows' worth of output however short its references reached.
# The late list holds any number of ascending runs now and that bound is gone
# -- 256 KB at a 200-byte reach was refused and is not. Both measurements are
# in the internal cost log under "Where the fixup ceiling actually is".
#
# One thing the span changes that is not the point: a group's five targets are
# five bytes of output, so a very short span inflates the file. Span 1 on a
# 64 KiB target emits 72,105 bytes rather than 65,555. The kit reports the
# output it got, so this is a note rather than a problem.
set -euo pipefail

WANT="${1:-65536}"

# Measured, not counted by hand: a block is 50 bytes of output and about 730
# of source, so a target of N bytes needs N/50 blocks and 14.6N of source. A
# megabyte of output is therefore 7.6 MB of source, which is the price of
# asking for this density at that size.
PER_BLOCK=50

BLOCKS=$(( (WANT + PER_BLOCK - 1) / PER_BLOCK ))

# 0 keeps the file this generated before the knob existed, byte for byte.
SPAN="${2:-0}"

awk -v n="$BLOCKS" -v span="$SPAN" '
BEGIN {
    print "; Generated by test/gen_worst.sh -- do not edit."
    if (span > 0) {
        printf "; Every reference is forward and reaches at most %d blocks.\n", span
    } else {
        print "; Every reference is forward and every definition is at the end."
    }
    print "    .assume adl=1"
    print "    .org 0x40000"
    print ""
    for (i = 0; i < n; i++) {
        blk(i)
        # The group this block belongs to is closed as soon as it is full, so
        # everything referring to it is settled here rather than at the end.
        if (span > 0 && (i + 1) % span == 0) {
            targets(int(i / span))
        }
    }
    if (span > 0) {
        # A last group that never filled still has references waiting on it.
        if (n % span != 0) {
            targets(int((n - 1) / span))
        }
    } else {
        # Every target in the file, defined here and nowhere else. Nothing
        # above this point can be settled until the assembler reaches it.
        targets(-1)
    }
}

# The five targets one group of blocks refers to. `g` of -1 is the span-0 file,
# whose targets are unsuffixed and are the only ones in it.
function targets(g,   sfx) {
    sfx = (g < 0) ? "" : sprintf("_%d", g)
    printf "far_a%s:\n    nop\n", sfx
    printf "far_b%s:\n    nop\n", sfx
    printf "far_c%s:\n    nop\n", sfx
    printf "far_d%s:\n    nop\n", sfx
    # `ret` rather than `nop`, as the end of the span-0 file has always been.
    printf "far_e%s:\n    ret\n", sfx
}

# Twenty-seven lines: one label definition, five branches to labels that do not
# exist yet, and twenty-one instructions that do not refer to anything.
function blk(i,   sfx) {
    sfx = (span > 0) ? sprintf("_%d", int(i / span)) : ""
    printf "w%d:\n", i                 # 1 definition
    printf "    ld   hl, far_a%s\n", sfx   # 5 references, four bytes each
    printf "    call far_b%s\n", sfx
    printf "    jp   far_c%s\n", sfx
    printf "    ld   de, far_d%s\n", sfx
    printf "    ld   bc, far_e%s\n", sfx
    print "    nop"                    # 21 that refer to nothing
    print "    inc  hl"
    print "    add  a, b"
    print "    ld   a, 0x42"
    print "    dec  c"
    print "    ld   ix, 0x1234"
    print "    or   a"
    print "    push af"
    print "    pop  af"
    print "    ld   (hl), a"
    print "    xor  a"
    print "    cp   b"
    print "    sbc  a, c"
    print "    rlca"
    print "    ex   de, hl"
    print "    scf"
    print "    ccf"
    print "    and  0x0F"
    print "    sub  d"
    print "    adc  a, e"
    print "    ld   sp, 0x8000"
    print ""
}
'
