#!/bin/bash
# Generates the synthetic benchmark source.
#
# The other benchmarks are real programs, which is what makes them worth
# timing -- but they are also a mixture of everything at once, so a change to
# instruction encoding shows up in them diluted by macro expansion, include
# handling and fixups. This one is deliberately narrow: a long run of straight
# instructions with no labels, no forward references, no macros and no
# includes, so nearly all of its time is lexing and encoding.
#
# It is generated rather than committed because it is 470 KB of nothing anyone
# needs to read, and generated *deterministically* because a benchmark whose
# input changes between runs is not a benchmark. No randomness: the line at
# index i is a pure function of i.
#
# Regenerating must produce a byte-identical file. If this script is ever
# changed, every timing taken before the change becomes incomparable with every
# timing after it -- so change it by adding a new generator, not by editing
# this one.
#
#   test/bench/gen_synth.sh [lines] > synth.s
#
# The default is sized to take roughly a minute on an Agon, which is long
# enough that the 10 ms clock granularity is noise.
set -euo pipefail

LINES="${1:-30000}"

awk -v n="$LINES" '
BEGIN {
    # A spread of encodings rather than the same instruction repeated: one and
    # two byte opcodes, DD/FD prefixed, ED prefixed, CB bit operations, 8 and
    # 16 bit immediates, and relative and absolute jumps. Repeating a single
    # instruction would measure one table row rather than the table.
    i = 0
    op[i++] = "    nop"
    op[i++] = "    ld a, 0x42"
    op[i++] = "    ld bc, 0x1234"
    op[i++] = "    add a, b"
    op[i++] = "    inc hl"
    op[i++] = "    ld (ix+8), a"
    op[i++] = "    bit 3, (iy+4)"
    op[i++] = "    res 7, b"
    op[i++] = "    set 0, (hl)"
    op[i++] = "    rlc d"
    op[i++] = "    ld de, 0x8000 + 16"
    op[i++] = "    sbc hl, bc"
    op[i++] = "    ldir"
    op[i++] = "    push af"
    op[i++] = "    pop iy"
    op[i++] = "    ex de, hl"
    op[i++] = "    cp 0x7F"
    op[i++] = "    and 0b10101010"
    op[i++] = "    or (hl)"
    op[i++] = "    xor 0x0F"
    op[i++] = "    call 0x040000"
    op[i++] = "    ret nz"
    op[i++] = "    im 2"
    op[i++] = "    rst 0x18"
    op[i++] = "    out (0xFE), a"
    op[i++] = "    in a, (0xFE)"
    op[i++] = "    ld a, (0x040100)"
    op[i++] = "    ld hl, (0x040200)"
    op[i++] = "    mlt de"
    op[i++] = "    lea ix, iy + 32"
    op[i++] = "    ld.sis hl, 0x1122"
    op[i++] = "    add hl, de"
    op[i++] = "    srl c"
    op[i++] = "    neg"
    op[i++] = "    scf"
    op[i++] = "    djnz $"
    op[i++] = "    jr $"
    op[i++] = "    dec sp"
    op[i++] = "    ld iy, 0x0400"
    op[i++] = "    adc a, (ix+0)"
    count = i

    print "; Generated by test/bench/gen_synth.sh -- do not edit."
    print "; Deterministic: line i is a pure function of i."
    print "    .assume adl=1"
    print "    .org 0x040000"

    for (k = 0; k < n; k++) {
        print op[k % count]

        # A comment every eleventh line and a blank every seventeenth, so the
        # lexer pays realistic amounts of skipping rather than none at all.
        # Coprime with the opcode cycle so the pattern does not align.
        if (k % 11 == 10) {
            print "; comment " k
        }
        if (k % 17 == 16) {
            print ""
        }
    }
    print "    ret"
}
' </dev/null
