#!/usr/bin/env python3
"""Generates src/isa_table.c from the reference assembler's instruction.c.

The 322 operand rows are the whole eZ80 instruction set. Transcribing them by
hand would put a wrong byte into any program that used a mistyped form, and the
reference's table is already tested against its own corpus -- so they are
copied mechanically instead.

Usage:  python3 tools/gen_isa.py <path-to-agon-ez80asm> > src/isa_table.c
"""
import re
import sys


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_isa.py <path-to-agon-ez80asm>")
    src = open(sys.argv[1] + "/src/instruction.c").read()

    # Operand rows, per mnemonic list.
    lists = {}
    for m in re.finditer(r'^operandlist_t operands_(\w+)\[\]\s*=\s*\{(.*?)^\};',
                         src, re.S | re.M):
        name, body = m.group(1), m.group(2)
        rows = []
        for line in body.splitlines():
            line = line.strip().rstrip(',').rstrip()
            if not line.startswith('{') or not line.endswith('}'):
                continue
            fields = [f.strip() for f in line[1:-1].split(',')]
            if len(fields) != 10:
                sys.exit("unexpected row in %s: %s" % (name, line))
            rows.append(fields)
        lists[name] = rows

    # Mnemonic table, keeping only the eZ80 entries; the ASSEMBLER rows are
    # directives, which zap handles in its own parser.
    insns = []
    tbl = re.search(r'^instruction_t instructions\[\] = \{(.*?)^\};',
                    src, re.S | re.M).group(1)
    for line in tbl.splitlines():
        m = re.match(r'\s*\{"(\w+)",\s*EZ80,\s*\w+,.*?operands_(\w+)', line)
        if m:
            insns.append((m.group(1), m.group(2)))

    used = set(listname for _, listname in insns)

    out = []
    out.append('/* GENERATED by tools/gen_isa.py -- do not edit by hand.')
    out.append(' *')
    out.append(' * Transcribed from the reference assembler\'s instruction.c. These rows are')
    out.append(' * the whole eZ80 instruction set; see the generator for why they are copied')
    out.append(' * mechanically rather than retyped.')
    out.append(' */')
    out.append('')
    out.append('#include "isa.h"')
    out.append('')

    for name in sorted(lists):
        if name not in used:
            continue
        out.append('static const isa_row rows_%s[] = {' % name)
        for f in lists[name]:
            (regA, condA, regB, condB, trA, trB, flags, cpu, prefix, opcode) = f
            out.append('    { %s, %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
                regA, condA, regB, condB,
                trA.replace('TRANSFORM_', 'TR_'),
                trB.replace('TRANSFORM_', 'TR_'),
                flags, cpu, prefix, opcode))
        out.append('};')
        out.append('')

    out.append('const isa_insn isa_table[] = {')
    for mnem, listname in insns:
        out.append('    { "%s", rows_%s, (uint8_t) (sizeof(rows_%s) / sizeof(isa_row)) },'
                   % (mnem, listname, listname))
    out.append('};')
    out.append('')
    out.append('const int isa_table_count = (int) (sizeof(isa_table) / sizeof(isa_insn));')

    sys.stdout.write('\n'.join(out) + '\n')
    sys.stderr.write("mnemonics: %d, lists: %d, rows: %d\n" % (
        len(insns), len(used), sum(len(lists[n]) for n in used)))


if __name__ == '__main__':
    main()
