/* GENERATED by tools/gen_isa.py -- do not edit by hand.
 *
 * Transcribed from the reference assembler's instruction.c. These rows are
 * the whole eZ80 instruction set; see the generator for why they are copied
 * mechanically rather than retyped.
 */

#include "isa.h"

static const isa_row rows_adc[] = {
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x8E },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x8C },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x8E },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xCE },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0x88 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x8E },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_EZ80, 0x00, 0x8C },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x8E },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xCE },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x88 },
    { R_HL, NOREQ, RS_RR, NOREQ, TR_NONE, TR_P, S_ANY, BIT_Z80, 0xED, 0x4A },
    { R_HL, NOREQ, R_SP, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0x7A },
};

static const isa_row rows_add[] = {
    { R_HL, NOREQ, RS_RR, NOREQ, TR_NONE, TR_P, S_ANY, BIT_Z80, 0x00, 0x09 },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0x80 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x86 },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x84 },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x86 },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xC6 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x86 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_EZ80, 0x00, 0x84 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x86 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xC6 },
    { R_HL, NOREQ, R_SP, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x39 },
    { RS_IXY, NOREQ, RS_RXY, NOREQ, TR_NONE, TR_P, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x09 },
    { RS_IXY, NOREQ, R_SP, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x39 },
};

static const isa_row rows_and[] = {
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xA0 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xE6 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xA6 },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xA4 },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xA6 },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xE6 },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0xA0 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xA6 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xA4 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xA6 },
};

static const isa_row rows_bit[] = {
    { RS_NONE, IMM|IMM_BIT, R_HL, INDIRECT, TR_Y, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x46 },
    { RS_NONE, IMM|IMM_BIT, RS_IXY, INDIRECT, TR_Y, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x46 },
    { RS_NONE, IMM|IMM_BIT, RS_R, NOREQ, TR_Y, TR_Z, F_NONE, BIT_Z80, 0xCB, 0x40 },
};

static const isa_row rows_call[] = {
    { RS_NONE, IMM|IMM_MMN, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xCD },
    { RS_NONE, NOREQ, RS_NONE, IMM|IMM_MMN, TR_CC, TR_NONE, F_CCOK|S_ANY, BIT_Z80, 0x00, 0xC4 },
};

static const isa_row rows_ccf[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x3F },
};

static const isa_row rows_cp[] = {
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xFE },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xB8 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xBE },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xFE },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0xB8 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xBE },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xBC },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xBE },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xBC },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xBE },
};

static const isa_row rows_cpd[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA9 },
};

static const isa_row rows_cpdr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB9 },
};

static const isa_row rows_cpi[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA1 },
};

static const isa_row rows_cpir[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB1 },
};

static const isa_row rows_cpl[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x2F },
};

static const isa_row rows_daa[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x27 },
};

static const isa_row rows_dec[] = {
    { RS_RR, NOREQ, RS_NONE, NOREQ, TR_P, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x0B },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Y, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x05 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x35 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR3, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x25 },
    { RS_IXY, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x2B },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x35 },
    { R_SP, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x3B },
};

static const isa_row rows_di[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xF3 },
};

static const isa_row rows_djnz[] = {
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_REL, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x10 },
};

static const isa_row rows_ei[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xFB },
};

static const isa_row rows_ex[] = {
    { R_DE, NOREQ, R_HL, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xEB },
    { R_AF, NOREQ, R_AF, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x08 },
    { R_SP, INDIRECT, R_HL, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xE3 },
    { R_SP, INDIRECT, RS_IXY, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xE3 },
};

static const isa_row rows_exx[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xD9 },
};

static const isa_row rows_halt[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x76 },
};

static const isa_row rows_im[] = {
    { RS_NONE, IMM|IMM_NSELECT, RS_NONE, NOREQ, TR_SELECT, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x46 },
};

static const isa_row rows_in[] = {
    { R_A, NOREQ, RS_NONE, INDIRECT|IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xDB },
    { R_C, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_U80, 0xED, 0x70 },
    { RS_R, NOREQ, R_BC, INDIRECT, TR_Y, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x40 },
    { RS_R, NOREQ, R_C, INDIRECT, TR_Y, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x40 },
};

static const isa_row rows_in0[] = {
    { RS_R, NOREQ, RS_NONE, INDIRECT|IMM|IMM_N, TR_Y, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x00 },
};

static const isa_row rows_inc[] = {
    { RS_RR, NOREQ, RS_NONE, NOREQ, TR_P, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x03 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Y, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x04 },
    { RS_IXY, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x23 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x34 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR3, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x24 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x34 },
    { R_SP, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x33 },
};

static const isa_row rows_ind[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xAA },
};

static const isa_row rows_ind2[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x8C },
};

static const isa_row rows_ind2r[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x9C },
};

static const isa_row rows_indm[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x8A },
};

static const isa_row rows_indmr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x9A },
};

static const isa_row rows_indr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xBA },
};

static const isa_row rows_indrx[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xCA },
};

static const isa_row rows_ini[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA2 },
};

static const isa_row rows_ini2[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x84 },
};

static const isa_row rows_ini2r[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x94 },
};

static const isa_row rows_inim[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x82 },
};

static const isa_row rows_inimr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x92 },
};

static const isa_row rows_inir[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB2 },
};

static const isa_row rows_inirx[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xC2 },
};

static const isa_row rows_jp[] = {
    { RS_NONE, CC, RS_NONE, IMM|IMM_MMN, TR_CC, TR_NONE, F_CCOK|S_SISLIL, BIT_Z80, 0x00, 0xC2 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xE9 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_SISLIL, BIT_Z80, 0x00, 0xE9 },
    { RS_NONE, IMM|IMM_MMN, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_SISLIL, BIT_Z80, 0x00, 0xC3 },
};

static const isa_row rows_jr[] = {
    { RS_NONE, CCA, RS_NONE, IMM|IMM_N, TR_CC, TR_REL, F_CCOK, BIT_Z80, 0x00, 0x20 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_REL, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x18 },
};

static const isa_row rows_ld[] = {
    { RS_RR, NOREQ, RS_NONE, IMM|IMM_MMN, TR_P, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x01 },
    { RS_R, NOREQ, RS_NONE, IMM|IMM_N, TR_Y, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x06 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x7E },
    { RS_NONE, INDIRECT|IMM|IMM_MMN, R_A, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x32 },
    { RS_R, NOREQ, RS_R, NOREQ, TR_Y, TR_Z, F_NONE, BIT_Z80, 0x00, 0x40 },
    { R_HL, NOREQ, RS_NONE, INDIRECT|IMM|IMM_MMN, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x2A },
    { R_A, NOREQ, RS_NONE, INDIRECT|IMM|IMM_MMN, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x3A },
    { RS_NONE, INDIRECT|IMM|IMM_MMN, R_HL, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x22 },
    { R_HL, INDIRECT, RS_R, NOREQ, TR_NONE, TR_Z, S_ANY, BIT_Z80, 0x00, 0x70 },
    { R_A, NOREQ, R_DE, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x1A },
    { RS_RR, NOREQ, R_HL, INDIRECT, TR_P, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x07 },
    { RS_RR, INDIRECT, R_A, NOREQ, TR_P, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x02 },
    { RS_IXY, NOREQ, RS_NONE, IMM|IMM_MMN, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x21 },
    { RS_IXY, INDIRECT, RS_RR, NOREQ, TR_NONE, TR_P, F_DISPA|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x0F },
    { RS_NONE, INDIRECT|IMM|IMM_MMN, RS_IXY, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x22 },
    { R_A, NOREQ, R_I, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x57 },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x7E },
    { R_A, NOREQ, R_MB, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0x6E },
    { R_A, NOREQ, R_R, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x5F },
    { R_A, NOREQ, R_BC, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x0A },
    { R_HL, NOREQ, R_I, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0xD7 },
    { R_HL, INDIRECT, R_IX, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x3F },
    { R_HL, INDIRECT, R_IY, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x3E },
    { R_HL, INDIRECT, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x36 },
    { R_HL, INDIRECT, RS_RR, NOREQ, TR_NONE, TR_P, S_ANY, BIT_EZ80, 0xED, 0x0F },
    { R_I, NOREQ, R_HL, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0xC7 },
    { R_I, NOREQ, R_A, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x47 },
    { RS_IR, NOREQ, RS_IR, NOREQ, TR_IR3, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x64 },
    { RS_IR, NOREQ, RS_NONE, IMM|IMM_N, TR_IR3, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x26 },
    { RS_IR, NOREQ, RS_AE, NOREQ, TR_IR3, TR_Z, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x60 },
    { R_IX, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x37 },
    { R_IY, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0x31 },
    { R_IX, NOREQ, R_IX, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x37 },
    { R_IY, NOREQ, R_IY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x37 },
    { R_IX, NOREQ, R_IY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x31 },
    { R_IY, NOREQ, R_IX, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x31 },
    { RS_IXY, NOREQ, RS_NONE, INDIRECT|IMM|IMM_MMN, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x2A },
    { R_IX, INDIRECT, R_IX, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x3F },
    { R_IY, INDIRECT, R_IY, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x3F },
    { R_IX, INDIRECT, R_IY, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x3E },
    { R_IY, INDIRECT, R_IX, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x3E },
    { RS_IXY, INDIRECT, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x36 },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_NONE, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x70 },
    { R_MB, NOREQ, R_A, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0x6D },
    { RS_NONE, INDIRECT|IMM|IMM_MMN, RS_RR, NOREQ, TR_NONE, TR_P, S_ANY, BIT_Z80, 0xED, 0x43 },
    { RS_NONE, INDIRECT|IMM|IMM_MMN, R_SP, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0x73 },
    { R_R, NOREQ, R_A, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x4F },
    { RS_R, NOREQ, R_HL, INDIRECT, TR_Y, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x46 },
    { RS_AE, NOREQ, RS_IR, NOREQ, TR_Y, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x44 },
    { RS_R, NOREQ, RS_IXY, INDIRECT, TR_Y, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x46 },
    { RS_RR, NOREQ, RS_IXY, INDIRECT, TR_P, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_EZ80, 0x00, 0x07 },
    { RS_RR, NOREQ, RS_NONE, INDIRECT|IMM|IMM_MMN, TR_P, TR_NONE, S_ANY, BIT_Z80, 0xED, 0x4B },
    { R_HL, INDIRECT, R_A, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x77 },
    { R_SP, NOREQ, R_HL, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xF9 },
    { R_SP, NOREQ, RS_IXY, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xF9 },
    { R_SP, NOREQ, RS_NONE, IMM|IMM_MMN, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x31 },
    { R_SP, NOREQ, RS_NONE, INDIRECT|IMM|IMM_MMN, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0x7B },
};

static const isa_row rows_ldd[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA8 },
};

static const isa_row rows_lddr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB8 },
};

static const isa_row rows_ldi[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA0 },
};

static const isa_row rows_ldir[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB0 },
};

static const isa_row rows_lea[] = {
    { RS_RR, NOREQ, R_IX, NOREQ, TR_P, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x02 },
    { R_IX, NOREQ, R_IX, NOREQ, TR_NONE, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x32 },
    { R_IY, NOREQ, R_IX, NOREQ, TR_NONE, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x55 },
    { R_IX, NOREQ, R_IY, NOREQ, TR_NONE, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x54 },
    { R_IY, NOREQ, R_IY, NOREQ, TR_NONE, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x33 },
    { RS_RR, NOREQ, R_IY, NOREQ, TR_P, TR_NONE, F_DISPB|S_ANY, BIT_EZ80, 0xED, 0x03 },
};

static const isa_row rows_mlt[] = {
    { RS_RR, NOREQ, RS_NONE, NOREQ, TR_P, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x4C },
    { R_SP, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x7C },
};

static const isa_row rows_neg[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x44 },
};

static const isa_row rows_nop[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x00 },
};

static const isa_row rows_or[] = {
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xB0 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xF6 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xB6 },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xB4 },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xB6 },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xF6 },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0xB0 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xB6 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xB4 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xB6 },
};

static const isa_row rows_otd2r[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xBC },
};

static const isa_row rows_otdm[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x8B },
};

static const isa_row rows_otdmr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x9B },
};

static const isa_row rows_otdr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xBB },
};

static const isa_row rows_otdrx[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xCB },
};

static const isa_row rows_oti2r[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xB4 },
};

static const isa_row rows_otim[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x83 },
};

static const isa_row rows_otimr[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x93 },
};

static const isa_row rows_otir[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xB3 },
};

static const isa_row rows_otirx[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xC3 },
};

static const isa_row rows_out[] = {
    { R_BC, INDIRECT, RS_R, NOREQ, TR_NONE, TR_Y, F_NONE, BIT_Z80, 0xED, 0x41 },
    { R_C, INDIRECT, RS_NONE, IMM, TR_NONE, TR_NONE, F_NONE, BIT_U80, 0xED, 0x71 },
    { R_C, INDIRECT, RS_R, NOREQ, TR_NONE, TR_Y, F_NONE, BIT_Z80, 0xED, 0x41 },
    { RS_NONE, INDIRECT|IMM|IMM_N, R_A, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xD3 },
};

static const isa_row rows_out0[] = {
    { RS_NONE, INDIRECT|IMM|IMM_N, RS_R, NOREQ, TR_NONE, TR_Y, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x01 },
};

static const isa_row rows_outd[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xAB },
};

static const isa_row rows_outd2[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xAC },
};

static const isa_row rows_outi[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0xA3 },
};

static const isa_row rows_outi2[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_EZ80, 0xED, 0xA4 },
};

static const isa_row rows_pea[] = {
    { R_IX, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|S_ANY, BIT_EZ80, 0xED, 0x65 },
    { R_IY, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|S_ANY, BIT_EZ80, 0xED, 0x66 },
};

static const isa_row rows_pop[] = {
    { RS_RR, NOREQ, RS_NONE, NOREQ, TR_P, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xC1 },
    { R_AF, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xF1 },
    { RS_IXY, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xE1 },
};

static const isa_row rows_push[] = {
    { RS_RR, NOREQ, RS_NONE, NOREQ, TR_P, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xC5 },
    { R_AF, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xF5 },
    { RS_IXY, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xE5 },
};

static const isa_row rows_res[] = {
    { RS_NONE, IMM|IMM_BIT, R_HL, INDIRECT, TR_Y, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x86 },
    { RS_NONE, IMM|IMM_BIT, RS_IXY, INDIRECT, TR_Y, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x86 },
    { RS_NONE, IMM|IMM_BIT, RS_R, NOREQ, TR_BIT, TR_Z, F_NONE, BIT_Z80, 0xCB, 0x80 },
};

static const isa_row rows_res0[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0x80 },
};

static const isa_row rows_res1[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0x88 },
};

static const isa_row rows_res2[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0x90 },
};

static const isa_row rows_res3[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0x98 },
};

static const isa_row rows_res4[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xA0 },
};

static const isa_row rows_res5[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xA8 },
};

static const isa_row rows_res6[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xB0 },
};

static const isa_row rows_res7[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xB8 },
};

static const isa_row rows_ret[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_LILLIS, BIT_Z80, 0x00, 0xC9 },
    { RS_NONE, CC, RS_NONE, NOREQ, TR_CC, TR_NONE, F_CCOK|S_LILLIS, BIT_Z80, 0x00, 0xC0 },
};

static const isa_row rows_reti[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_LILLIS, BIT_Z80, 0xED, 0x4D },
};

static const isa_row rows_retn[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_LILLIS, BIT_Z80, 0xED, 0x45 },
};

static const isa_row rows_rl[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x16 },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x10 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x16 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x10 },
};

static const isa_row rows_rla[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x17 },
};

static const isa_row rows_rlc[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x06 },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x00 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x06 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x00 },
};

static const isa_row rows_rlca[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x07 },
};

static const isa_row rows_rld[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x6F },
};

static const isa_row rows_rr[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x1E },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x18 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x1E },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x18 },
};

static const isa_row rows_rra[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x1F },
};

static const isa_row rows_rrc[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x0E },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x08 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x0E },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x08 },
};

static const isa_row rows_rrca[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x0F },
};

static const isa_row rows_rrd[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xED, 0x67 },
};

static const isa_row rows_rsmix[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0x7E },
};

static const isa_row rows_rst[] = {
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_N, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xC7 },
};

static const isa_row rows_sbc[] = {
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x9E },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x9C },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x9E },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xDE },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0x98 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x9E },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x9C },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x9E },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xDE },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x98 },
    { R_HL, NOREQ, RS_RR, NOREQ, TR_NONE, TR_P, S_ANY, BIT_Z80, 0xED, 0x42 },
    { R_HL, NOREQ, R_SP, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xED, 0x72 },
};

static const isa_row rows_scf[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x37 },
};

static const isa_row rows_set[] = {
    { RS_NONE, IMM|IMM_BIT, R_HL, INDIRECT, TR_Y, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0xC6 },
    { RS_NONE, IMM|IMM_BIT, RS_IXY, INDIRECT, TR_Y, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0xC6 },
    { RS_NONE, IMM|IMM_BIT, RS_R, NOREQ, TR_BIT, TR_Z, F_NONE, BIT_Z80, 0xCB, 0xC0 },
};

static const isa_row rows_set0[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xC0 },
};

static const isa_row rows_set1[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xC8 },
};

static const isa_row rows_set2[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xD0 },
};

static const isa_row rows_set3[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xD8 },
};

static const isa_row rows_set4[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xE0 },
};

static const isa_row rows_set5[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xE8 },
};

static const isa_row rows_set6[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xF0 },
};

static const isa_row rows_set7[] = {
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK, BIT_U80, 0xCB, 0xF8 },
};

static const isa_row rows_sla[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x26 },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x20 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x26 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x20 },
};

static const isa_row rows_sll[] = {
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_U80, 0xCB, 0x30 },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x30 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_Z, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x36 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x36 },
};

static const isa_row rows_slp[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x76 },
};

static const isa_row rows_sra[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x2E },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x28 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x2E },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x28 },
};

static const isa_row rows_srl[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0xCB, 0x3E },
    { RS_IXY, INDIRECT, RS_R, NOREQ, TR_Z, TR_Z, F_DISPA|F_DDFDOK|S_ANY, BIT_U80, 0xCB, 0x38 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0xCB, 0x3E },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0xCB, 0x38 },
};

static const isa_row rows_stmix[] = {
    { RS_NONE, NOREQ, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_EZ80, 0xED, 0x7D },
};

static const isa_row rows_sub[] = {
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x96 },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0x96 },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x94 },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x96 },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xD6 },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0x90 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0x94 },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0x96 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xD6 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0x90 },
};

static const isa_row rows_tst[] = {
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x34 },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x64 },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Y, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x04 },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z180|BIT_EZ80, 0xED, 0x34 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x64 },
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Y, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x04 },
};

static const isa_row rows_tstio[] = {
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z180|BIT_EZ80, 0xED, 0x74 },
};

static const isa_row rows_xor[] = {
    { RS_R, NOREQ, RS_NONE, NOREQ, TR_Z, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xA8 },
    { RS_NONE, IMM|IMM_N, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xEE },
    { R_HL, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xAE },
    { R_A, NOREQ, R_HL, INDIRECT, TR_NONE, TR_NONE, S_ANY, BIT_Z80, 0x00, 0xAE },
    { R_A, NOREQ, RS_IR, NOREQ, TR_NONE, TR_IR0, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xAC },
    { R_A, NOREQ, RS_IXY, INDIRECT, TR_NONE, TR_NONE, F_DISPB|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xAE },
    { R_A, NOREQ, RS_NONE, IMM|IMM_N, TR_NONE, TR_NONE, F_NONE, BIT_Z80, 0x00, 0xEE },
    { R_A, NOREQ, RS_R, NOREQ, TR_NONE, TR_Z, F_NONE, BIT_Z80, 0x00, 0xA8 },
    { RS_IR, NOREQ, RS_NONE, NOREQ, TR_IR0, TR_NONE, F_DDFDOK, BIT_U80|BIT_EZ80, 0x00, 0xAC },
    { RS_IXY, INDIRECT, RS_NONE, NOREQ, TR_NONE, TR_NONE, F_DISPA|F_DDFDOK|S_ANY, BIT_Z80, 0x00, 0xAE },
};

const isa_insn isa_table[] = {
    { "adc", rows_adc, (uint8_t) (sizeof(rows_adc) / sizeof(isa_row)) },
    { "add", rows_add, (uint8_t) (sizeof(rows_add) / sizeof(isa_row)) },
    { "and", rows_and, (uint8_t) (sizeof(rows_and) / sizeof(isa_row)) },
    { "bit", rows_bit, (uint8_t) (sizeof(rows_bit) / sizeof(isa_row)) },
    { "call", rows_call, (uint8_t) (sizeof(rows_call) / sizeof(isa_row)) },
    { "ccf", rows_ccf, (uint8_t) (sizeof(rows_ccf) / sizeof(isa_row)) },
    { "cp", rows_cp, (uint8_t) (sizeof(rows_cp) / sizeof(isa_row)) },
    { "cpd", rows_cpd, (uint8_t) (sizeof(rows_cpd) / sizeof(isa_row)) },
    { "cpdr", rows_cpdr, (uint8_t) (sizeof(rows_cpdr) / sizeof(isa_row)) },
    { "cpi", rows_cpi, (uint8_t) (sizeof(rows_cpi) / sizeof(isa_row)) },
    { "cpir", rows_cpir, (uint8_t) (sizeof(rows_cpir) / sizeof(isa_row)) },
    { "cpl", rows_cpl, (uint8_t) (sizeof(rows_cpl) / sizeof(isa_row)) },
    { "daa", rows_daa, (uint8_t) (sizeof(rows_daa) / sizeof(isa_row)) },
    { "dec", rows_dec, (uint8_t) (sizeof(rows_dec) / sizeof(isa_row)) },
    { "di", rows_di, (uint8_t) (sizeof(rows_di) / sizeof(isa_row)) },
    { "djnz", rows_djnz, (uint8_t) (sizeof(rows_djnz) / sizeof(isa_row)) },
    { "ei", rows_ei, (uint8_t) (sizeof(rows_ei) / sizeof(isa_row)) },
    { "ex", rows_ex, (uint8_t) (sizeof(rows_ex) / sizeof(isa_row)) },
    { "exx", rows_exx, (uint8_t) (sizeof(rows_exx) / sizeof(isa_row)) },
    { "halt", rows_halt, (uint8_t) (sizeof(rows_halt) / sizeof(isa_row)) },
    { "im", rows_im, (uint8_t) (sizeof(rows_im) / sizeof(isa_row)) },
    { "in", rows_in, (uint8_t) (sizeof(rows_in) / sizeof(isa_row)) },
    { "in0", rows_in0, (uint8_t) (sizeof(rows_in0) / sizeof(isa_row)) },
    { "inc", rows_inc, (uint8_t) (sizeof(rows_inc) / sizeof(isa_row)) },
    { "ind", rows_ind, (uint8_t) (sizeof(rows_ind) / sizeof(isa_row)) },
    { "ind2", rows_ind2, (uint8_t) (sizeof(rows_ind2) / sizeof(isa_row)) },
    { "ind2r", rows_ind2r, (uint8_t) (sizeof(rows_ind2r) / sizeof(isa_row)) },
    { "indm", rows_indm, (uint8_t) (sizeof(rows_indm) / sizeof(isa_row)) },
    { "indmr", rows_indmr, (uint8_t) (sizeof(rows_indmr) / sizeof(isa_row)) },
    { "indr", rows_indr, (uint8_t) (sizeof(rows_indr) / sizeof(isa_row)) },
    { "indrx", rows_indrx, (uint8_t) (sizeof(rows_indrx) / sizeof(isa_row)) },
    { "ini", rows_ini, (uint8_t) (sizeof(rows_ini) / sizeof(isa_row)) },
    { "ini2", rows_ini2, (uint8_t) (sizeof(rows_ini2) / sizeof(isa_row)) },
    { "ini2r", rows_ini2r, (uint8_t) (sizeof(rows_ini2r) / sizeof(isa_row)) },
    { "inim", rows_inim, (uint8_t) (sizeof(rows_inim) / sizeof(isa_row)) },
    { "inimr", rows_inimr, (uint8_t) (sizeof(rows_inimr) / sizeof(isa_row)) },
    { "inir", rows_inir, (uint8_t) (sizeof(rows_inir) / sizeof(isa_row)) },
    { "inirx", rows_inirx, (uint8_t) (sizeof(rows_inirx) / sizeof(isa_row)) },
    { "jp", rows_jp, (uint8_t) (sizeof(rows_jp) / sizeof(isa_row)) },
    { "jr", rows_jr, (uint8_t) (sizeof(rows_jr) / sizeof(isa_row)) },
    { "ld", rows_ld, (uint8_t) (sizeof(rows_ld) / sizeof(isa_row)) },
    { "ldd", rows_ldd, (uint8_t) (sizeof(rows_ldd) / sizeof(isa_row)) },
    { "lddr", rows_lddr, (uint8_t) (sizeof(rows_lddr) / sizeof(isa_row)) },
    { "ldi", rows_ldi, (uint8_t) (sizeof(rows_ldi) / sizeof(isa_row)) },
    { "ldir", rows_ldir, (uint8_t) (sizeof(rows_ldir) / sizeof(isa_row)) },
    { "lea", rows_lea, (uint8_t) (sizeof(rows_lea) / sizeof(isa_row)) },
    { "mlt", rows_mlt, (uint8_t) (sizeof(rows_mlt) / sizeof(isa_row)) },
    { "neg", rows_neg, (uint8_t) (sizeof(rows_neg) / sizeof(isa_row)) },
    { "nop", rows_nop, (uint8_t) (sizeof(rows_nop) / sizeof(isa_row)) },
    { "or", rows_or, (uint8_t) (sizeof(rows_or) / sizeof(isa_row)) },
    { "otd2r", rows_otd2r, (uint8_t) (sizeof(rows_otd2r) / sizeof(isa_row)) },
    { "otdm", rows_otdm, (uint8_t) (sizeof(rows_otdm) / sizeof(isa_row)) },
    { "otdmr", rows_otdmr, (uint8_t) (sizeof(rows_otdmr) / sizeof(isa_row)) },
    { "otdr", rows_otdr, (uint8_t) (sizeof(rows_otdr) / sizeof(isa_row)) },
    { "otdrx", rows_otdrx, (uint8_t) (sizeof(rows_otdrx) / sizeof(isa_row)) },
    { "oti2r", rows_oti2r, (uint8_t) (sizeof(rows_oti2r) / sizeof(isa_row)) },
    { "otim", rows_otim, (uint8_t) (sizeof(rows_otim) / sizeof(isa_row)) },
    { "otimr", rows_otimr, (uint8_t) (sizeof(rows_otimr) / sizeof(isa_row)) },
    { "otir", rows_otir, (uint8_t) (sizeof(rows_otir) / sizeof(isa_row)) },
    { "otirx", rows_otirx, (uint8_t) (sizeof(rows_otirx) / sizeof(isa_row)) },
    { "out", rows_out, (uint8_t) (sizeof(rows_out) / sizeof(isa_row)) },
    { "out0", rows_out0, (uint8_t) (sizeof(rows_out0) / sizeof(isa_row)) },
    { "outd", rows_outd, (uint8_t) (sizeof(rows_outd) / sizeof(isa_row)) },
    { "outd2", rows_outd2, (uint8_t) (sizeof(rows_outd2) / sizeof(isa_row)) },
    { "outi", rows_outi, (uint8_t) (sizeof(rows_outi) / sizeof(isa_row)) },
    { "outi2", rows_outi2, (uint8_t) (sizeof(rows_outi2) / sizeof(isa_row)) },
    { "pea", rows_pea, (uint8_t) (sizeof(rows_pea) / sizeof(isa_row)) },
    { "pop", rows_pop, (uint8_t) (sizeof(rows_pop) / sizeof(isa_row)) },
    { "push", rows_push, (uint8_t) (sizeof(rows_push) / sizeof(isa_row)) },
    { "res", rows_res, (uint8_t) (sizeof(rows_res) / sizeof(isa_row)) },
    { "res0", rows_res0, (uint8_t) (sizeof(rows_res0) / sizeof(isa_row)) },
    { "res1", rows_res1, (uint8_t) (sizeof(rows_res1) / sizeof(isa_row)) },
    { "res2", rows_res2, (uint8_t) (sizeof(rows_res2) / sizeof(isa_row)) },
    { "res3", rows_res3, (uint8_t) (sizeof(rows_res3) / sizeof(isa_row)) },
    { "res4", rows_res4, (uint8_t) (sizeof(rows_res4) / sizeof(isa_row)) },
    { "res5", rows_res5, (uint8_t) (sizeof(rows_res5) / sizeof(isa_row)) },
    { "res6", rows_res6, (uint8_t) (sizeof(rows_res6) / sizeof(isa_row)) },
    { "res7", rows_res7, (uint8_t) (sizeof(rows_res7) / sizeof(isa_row)) },
    { "ret", rows_ret, (uint8_t) (sizeof(rows_ret) / sizeof(isa_row)) },
    { "reti", rows_reti, (uint8_t) (sizeof(rows_reti) / sizeof(isa_row)) },
    { "retn", rows_retn, (uint8_t) (sizeof(rows_retn) / sizeof(isa_row)) },
    { "rl", rows_rl, (uint8_t) (sizeof(rows_rl) / sizeof(isa_row)) },
    { "rla", rows_rla, (uint8_t) (sizeof(rows_rla) / sizeof(isa_row)) },
    { "rlc", rows_rlc, (uint8_t) (sizeof(rows_rlc) / sizeof(isa_row)) },
    { "rlca", rows_rlca, (uint8_t) (sizeof(rows_rlca) / sizeof(isa_row)) },
    { "rld", rows_rld, (uint8_t) (sizeof(rows_rld) / sizeof(isa_row)) },
    { "rr", rows_rr, (uint8_t) (sizeof(rows_rr) / sizeof(isa_row)) },
    { "rra", rows_rra, (uint8_t) (sizeof(rows_rra) / sizeof(isa_row)) },
    { "rrc", rows_rrc, (uint8_t) (sizeof(rows_rrc) / sizeof(isa_row)) },
    { "rrca", rows_rrca, (uint8_t) (sizeof(rows_rrca) / sizeof(isa_row)) },
    { "rrd", rows_rrd, (uint8_t) (sizeof(rows_rrd) / sizeof(isa_row)) },
    { "rsmix", rows_rsmix, (uint8_t) (sizeof(rows_rsmix) / sizeof(isa_row)) },
    { "rst", rows_rst, (uint8_t) (sizeof(rows_rst) / sizeof(isa_row)) },
    { "sbc", rows_sbc, (uint8_t) (sizeof(rows_sbc) / sizeof(isa_row)) },
    { "scf", rows_scf, (uint8_t) (sizeof(rows_scf) / sizeof(isa_row)) },
    { "set", rows_set, (uint8_t) (sizeof(rows_set) / sizeof(isa_row)) },
    { "set0", rows_set0, (uint8_t) (sizeof(rows_set0) / sizeof(isa_row)) },
    { "set1", rows_set1, (uint8_t) (sizeof(rows_set1) / sizeof(isa_row)) },
    { "set2", rows_set2, (uint8_t) (sizeof(rows_set2) / sizeof(isa_row)) },
    { "set3", rows_set3, (uint8_t) (sizeof(rows_set3) / sizeof(isa_row)) },
    { "set4", rows_set4, (uint8_t) (sizeof(rows_set4) / sizeof(isa_row)) },
    { "set5", rows_set5, (uint8_t) (sizeof(rows_set5) / sizeof(isa_row)) },
    { "set6", rows_set6, (uint8_t) (sizeof(rows_set6) / sizeof(isa_row)) },
    { "set7", rows_set7, (uint8_t) (sizeof(rows_set7) / sizeof(isa_row)) },
    { "sla", rows_sla, (uint8_t) (sizeof(rows_sla) / sizeof(isa_row)) },
    { "sll", rows_sll, (uint8_t) (sizeof(rows_sll) / sizeof(isa_row)) },
    { "slp", rows_slp, (uint8_t) (sizeof(rows_slp) / sizeof(isa_row)) },
    { "sra", rows_sra, (uint8_t) (sizeof(rows_sra) / sizeof(isa_row)) },
    { "srl", rows_srl, (uint8_t) (sizeof(rows_srl) / sizeof(isa_row)) },
    { "stmix", rows_stmix, (uint8_t) (sizeof(rows_stmix) / sizeof(isa_row)) },
    { "sub", rows_sub, (uint8_t) (sizeof(rows_sub) / sizeof(isa_row)) },
    { "tst", rows_tst, (uint8_t) (sizeof(rows_tst) / sizeof(isa_row)) },
    { "tstio", rows_tstio, (uint8_t) (sizeof(rows_tstio) / sizeof(isa_row)) },
    { "xor", rows_xor, (uint8_t) (sizeof(rows_xor) / sizeof(isa_row)) },
};

const int isa_table_count = (int) (sizeof(isa_table) / sizeof(isa_insn));
